---
name: activity-02
break: true
indent: 4
---

writing:
    activity.md:
        ConfirmFileExists
        CountFileParagraphs --count 1
        CountMarkdownTags --tag "heading" --count 5
        CountMarkdownTags --tag "list" --count 1
        CountMarkdownTags --tag "code_block" --count 1
        CountMarkdownTags --tag "link" --count 1
        CountMarkdownTags --tag "image" --count 1
        CountMarkdownTags --tag "strong" --count 1
        CountMarkdownTags --tag "emph" --count 1
        mdl --rules ~MD009,~MD013,~MD0022,~MD026